name: GitLab to GitHub Sync (with Submodules)

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3

      - name: Pull from GitLab (with submodules)
        uses: actions/checkout@v3
        with:
          repository: 'sleepy-cat-1/weblanding'
          token: ${{ secrets.GITLAB_TOKEN }}
          submodules: true 
          fetch-depth: 0 

      - name: Install Git (just in case)
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Copy GitLab files to GitHub repo
        run: rsync -av --delete gitlab-repo/* ./

      - name: Commit and Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Sync from GitLab (with submodules)"
          branch: main