name: Sync from GitLab

on:
  repository_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add GitLab remote
        run: git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ secrets.GITLAB_REPO_PATH }}.git

      - name: Fetch from GitLab
        run: git fetch --all --tags --prune gitlab

      - name: Merge changes from GitLab
        run: git merge --allow-unrelated-histories gitlab/${{ secrets.GITLAB_BRANCH }}

      - name: Push to GitHub
        run: git push