name: GitLab to GitHub Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: '/5 * * * *'

permissions:
  contents: write  # Allow push access to the repository

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # (Add your setup for GitLab access here)
      - name: Sync from GitLab
        run: |
          git remote add gitlab ${{ secrets.GITLAB_URL }}
          git fetch --all --tags --prune
          git checkout main
          git merge --allow-unrelated-histories gitlab/main
          git push --force